# Example configuration file
# Copy this file and rename it to application-local.properties
# Update the values based on your local setup

myTestKey=This value is from LOCAL properties file

github.baseurl=https://api.github.com
github.baseurl.path=/search/repositories

# Change this to your local logging directory
logging.file.name=YOUR_LOGGING_PATH/github-provider.log
logging.level.root=INFO

# Change the database name according to your local PostgreSQL setup
spring.datasource.url=jdbc:postgresql://localhost:5432/YOUR_DB_NAME

# Add your PostgreSQL credentials
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true