myTestKey=This value is from LOCAL properties file

github.baseurl=https://api.github.com
github.baseurl.path=/search/repositories

logging.file.name=D:/Workspace/GithubProviderRepo/logs/github-provider.log
logging.level.root=INFO

spring.datasource.url=jdbc:postgresql://localhost:5432/github_repo_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true